[build]
  base    = "react-pwa"
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "react-pwa/netlify/functions"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Cache-Control = "no-cache"
